apiVersion: v1
kind: Pod
metadata:
  name: data-retrieval-pod
spec:
  containers:
  - name: retrieval
    image: busybox
    command: ['sleep', '3600']  # Pod will stay alive for 1 hour
    volumeMounts:
    - name: data-volume
      mountPath: /app/data
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: taxi-rides-pvc
